//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AFLTestEntities : DbContext
    {
        public AFLTestEntities()
            : base("name=AFLTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressTable> AddressTables { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Cost> Costs { get; set; }
        public virtual DbSet<CostType> CostTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubCost> SubCosts { get; set; }
        public virtual DbSet<SubOrganization> SubOrganizations { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
    }
}
