//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public System.Guid User_ID { get; set; }
        public System.Guid UserType_ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Survey_ID { get; set; }
        public System.Guid Costs_ID { get; set; }
    
        public virtual Cost Cost { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
