//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cost()
        {
            this.AppUsers = new HashSet<AppUser>();
            this.SubOrganizations = new HashSet<SubOrganization>();
        }
    
        public System.Guid Costs_ID { get; set; }
        public System.Guid Costs { get; set; }
        public System.Guid Budget_ID { get; set; }
        public System.Guid Cost_Type_ID { get; set; }
    
        public virtual Budget Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual CostType CostType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubOrganization> SubOrganizations { get; set; }
    }
}
