//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostType()
        {
            this.Costs = new HashSet<Cost>();
        }
    
        public System.Guid Cost_Type_ID { get; set; }
        public string Cost_Type { get; set; }
        public System.Guid SubCost_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Costs { get; set; }
        public virtual SubCost SubCost { get; set; }
    }
}
