//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public System.Guid Region_ID { get; set; }
        public string Region1 { get; set; }
        public System.Guid State_ID { get; set; }
    
        public virtual State State { get; set; }
    }
}
