//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCost()
        {
            this.CostTypes = new HashSet<CostType>();
        }
    
        public System.Guid SubCost_ID { get; set; }
        public string SubCost1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostType> CostTypes { get; set; }
    }
}
