//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL_GLOBAL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubOrganization()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public System.Guid SubOrgID { get; set; }
        public string SobOrgName { get; set; }
        public System.Guid AddressID { get; set; }
        public System.Guid Budget_ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Costs_ID { get; set; }
    
        public virtual AddressTable AddressTable { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual Cost Cost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
